"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.codeFenceRx = exports.tableRowRx = exports.hrRx = exports.endsWithMarkRx = exports.endsWithSemiRx = exports.endsWithColonRx = exports.headingRx = exports.h2Rx = exports.lstItemRx = exports.numItemRx = exports.bulItemRx = void 0;
exports.bulItemRx = /^[-+*]\s/;
exports.numItemRx = /^\d+\.\s+/;
exports.lstItemRx = /^([-+*]\s|\d+\.\s)/;
exports.h2Rx = /^##(?!\#)\s+\S/;
exports.headingRx = /^#/;
exports.endsWithColonRx = /:$/;
exports.endsWithSemiRx = /;$/;
exports.endsWithMarkRx = /[.!?:;]$/;
exports.hrRx = /^(-{3,}|\*{3,}|_{3,})$/;
exports.tableRowRx = /^\|/;
exports.codeFenceRx = /^```/;
