"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.codeFenceRx = exports.endsWithMarkRx = exports.endsWithSemiRx = exports.endsWithColonRx = exports.h2Rx = exports.lstItemRx = exports.numItemRx = exports.bulItemRx = exports.subNumItemRx = void 0;
exports.subNumItemRx = /^\d+(?:\.\d+)+\s+/;
exports.bulItemRx = /^[-+*]\s/;
exports.numItemRx = /^\d+(?:\.\d+)+\s+|\d+\.\s+/;
exports.lstItemRx = /^([-+*]\s|\d+(?:\.\d+)+\s|\d+\.\s)/;
exports.h2Rx = /^##(?!\#)\s+\S/;
exports.endsWithColonRx = /:$/;
exports.endsWithSemiRx = /;$/;
exports.endsWithMarkRx = /[.!?:;]$/;
exports.codeFenceRx = /^```/;
